name: CreateReleaseBranch

on:
  workflow_dispatch:

jobs:
  run-python-script:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v5 
        with:
          python-version: '3.11'
      
      - name: Create release branch
        run: python create_release_gh_actions.py