name: MergeDown

on:
  workflow_dispatch:

jobs:
  run-python-script:
    runs-on: ubuntu-latest
    
    permissions: 
      contents: write
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v5 
        with:
          python-version: '3.11'
      
      - name: merge_down_gh_actions
        run: python ./git-scripts-gh-actions/create_release_gh_actions.py